apiVersion: apps/v1
kind: Deployment
metadata:
  name: frt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frt
  template:
    metadata:
      labels:
        app: frt
    spec:
      containers:
      - image: okteto.dev/frt:latest
        name: frt
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "ca991fd6-5017-4684-b824-0fab8c419eb6"
        - name: Vless_Path
          value: "/xcsfdsg4hg"
        - name: Vmess_UUID
          value: "ca991fd6-5017-4684-b824-0fab8c419eb6"
        - name: Vmess_Path
          value: "/t436ggw3zs"
        - name: Share_Path
          value: "/v2link"
