apiVersion: apps/v1
kind: Deployment
metadata:
  name: myu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myu
  template:
    metadata:
      labels:
        app: myu
    spec:
      containers:
      - image: okteto.dev/myu:latest
        name: myu
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "99af137f-3a11-4df6-9216-c8a37100b991"
        - name: Vless_Path
          value: "/fgh76u4wrgjyu"
        - name: Vmess_UUID
          value: "99af137f-3a11-4df6-9216-c8a37100b991"
        - name: Vmess_Path
          value: "/fdbjui75u56ehtd"
        - name: Share_Path
          value: "/v2link"
